version: '3.8'

services:
  node:
    build:
      context: ./node-app
    volumes:
      - ./node-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafionode2
      MYSQL_USER: usuario
      MYSQL_PASSWORD: teste
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - node

volumes:
  mysql_data:
